sonar.verbose=true
sonar.organization=sahil01
sonar.projectKey=sahil01_sonar-qube-test
sonar.projectName=Sonar-Qube test
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
